### PR TITLE
Drop a bunch of unused code

### PR DESCRIPTION
**Pull request by andyg0808**
We're not using a bunch of the classes in our copy of Mootools. Let's delete them and save ourselves some bytes!

qa_req 0
This will be QAed as part of ifixit/ifixit#36178

### CODE REVIEW

**Comment by jarstelfox** [comment]
CR 🌵

**Comment by djmetzle** [comment]
Nice! CR :heavy_minus_sign:

**Comment by probablyian** [comment]
_Yeeeeeessssssss_ CR 🤘

**Comment by andyg0808** [comment]
Someday, let's merge this into our main repo and delete this repo.
Someday even later, let's delete this altogether.

**Pull request merged**
